#pragma once

#include "../constants.h"

#define CARD_WIDTH 150
#define CARD_HEIGHT 210

#define HAND_STEP_X 28
#define HAND_ORIGIN_X (WINDOW_WIDTH/2.f - CARD_WIDTH/2.f - HAND_STEP_X*2.f)
#define HAND_ORIGIN_Y_DEALER 200
#define HAND_ORIGIN_Y_PLAYER 440

#define DECK_ORIGIN_X 120
#define DECK_ORIGIN_Y (HAND_ORIGIN_Y_DEALER/2.f + HAND_ORIGIN_Y_PLAYER/2.f)

#define HAND_SPLITTING_Y_DEALER (HAND_ORIGIN_Y_DEALER - 140)
#define HAND_SPLITTING_Y_PLAYER (HAND_SPLITTING_Y_DEALER + CARD_HEIGHT + 30)
#define SPLIT_HAND_SPLITTING_Y_PLAYER (HAND_SPLITTING_Y_PLAYER + CARD_HEIGHT + 30)