#pragma once

typedef enum CARD_LOCATION {
    CARD_LOCATION_DECK,
    CARD_LOCATION_DEALER_HAND,
    CARD_LOCATION_PLAYER_HAND,
    CARD_LOCATION_PLAYER_SPLIT_HAND
} CARD_LOCATION;

typedef enum GAME_STATE {
    _GAME_STATE_NONE,
    GAME_STATE_BETTING,
    GAME_STATE_PLAYING,
    GAME_STATE_BETTING_PLAYING,
    GAME_STATE_PLAYING_SPLIT,
    GAME_STATE_FIN,
} GAME_STATE;

typedef enum CHEQUE_VALUE {
    _CHEQUE_VALUE_NONE = 0,
    CHEQUE_VALUE_ONE = 1,
    CHEQUE_VALUE_FIVE = 5,
    CHEQUE_VALUE_TEN = 10,
    CHEQUE_VALUE_TWENTY_FIVE = 25,
    CHEQUE_VALUE_HUNDRED = 100,
    CHEQUE_VALUE_FIVE_HUNDRED = 500,
    CHEQUE_VALUE_ONE_K = 1000,
    CHEQUE_VALUE_FIVE_K = 5000,
    CHEQUE_VALUE_TWENTY_FIVE_K = 25000,
    CHEQUE_VALUE_HUNDRED_K = 100000
} CHEQUE_VALUE;