#pragma once

#include "../constants.h"

#define MOVE_BUTTON_WIDTH 168
#define MOVE_BUTTON_HEIGHT 70
#define MOVE_BUTTON_SEPARATION_X 20
#define MOVE_BUTTON_STEP_X (MOVE_BUTTON_WIDTH + MOVE_BUTTON_SEPARATION_X)
#define MOVE_BUTTON_ORIGIN_X (WINDOW_WIDTH/2.f - MOVE_BUTTON_WIDTH/2.f)
#define MOVE_BUTTON_ORIGIN_Y (WINDOW_HEIGHT - 160)

#define STACK_BUTTON_ORIGIN_X (WINDOW_WIDTH/2.f - CHIP_BUTTON_WIDTH/2.f)
#define STACK_BUTTON_ORIGIN_Y (WINDOW_HEIGHT/2.f - CHIP_BUTTON_HEIGHT*2.2f)

#define CHIP_BUTTON_WIDTH 122
#define CHIP_BUTTON_HEIGHT 134
#define CHIP_BUTTON_SEPARATION_X 10
#define CHIP_BUTTON_SEPARATION_Y 20
#define CHIP_BUTTON_STEP_X (CHIP_BUTTON_WIDTH + CHIP_BUTTON_SEPARATION_X)
#define CHIP_BUTTON_ORIGIN_X (WINDOW_WIDTH/2.f - CHIP_BUTTON_WIDTH/2.f - CHIP_BUTTON_STEP_X*2.f)
#define CHIP_BUTTON_ORIGIN_Y (WINDOW_HEIGHT/2.f - CHIP_BUTTON_HEIGHT*1.4f)

#define ABS(a) (((a) < 0) ? -(a) : (a))
#define CHIP_BUTTON_X(i) \
    CHIP_BUTTON_X_ORIGIN \
    + (i % 5) * (CHIP_BUTTON_WIDTH + CHIP_BUTTON_SEPARATION_X)
#define CHIP_BUTTON_Y(i) \
    CHIP_BUTTON_Y_ORIGIN \
    + (i / 5) * (CHIP_BUTTON_HEIGHT+CHIP_BUTTON_SEPARATION_Y) \
    - 30 * ABS(2 - (i % 5)) + 60